In [1]:
#data set form kaggle :link:  https://www.kaggle.com/competitions/fake-news/data?select=train.csv

import pandas as pd

# Load the dataset with the correct delimiter
df = pd.read_csv("train.csv")

In [2]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [3]:
x = df.drop('label', axis = 1) # ye sab mere independent feature hai

In [4]:
y = df['label']  # thats my output level

In [5]:
x

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [6]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

In [7]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.12.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (5.29.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.32.2)
Requirement already satisfied: setuptools in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (69.5.1)
Requirement already satisfied: six>=1.12.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\91979\appdata\roaming\python\python312\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.68.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.11.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.43.0)
Requirement already satisfied: rich in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (13.3.5)
Requirement already satisfied: namex in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install tensorflow==2.18.0

Requirement already satisfied: tensorflow==2.18.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow==2.18.0) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (24.12.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.4.0)
Requirement already satisfied: packaging in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (5.29.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.32.2)
Requirement already satisfied: setuptools in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (69.5.1)
Requirement already satisfied: six>=1.12.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\91979\appdata\roaming\python\python312\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (1.68.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.11.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.43.0)
Requirement already satisfied: rich in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (13.3.5)
Requirement already satisfied: namex in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.0.8)
Requirement already satisfied: optree in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow==2.18.0) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow==2.18.0) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import tensorflow as tf
print(tf.__version__)

2.18.0

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [11]:
#vacobalury size
voc_size=5000

In [12]:
messages = x.copy()

In [13]:
messages

,id,title,author,text
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ..."
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...
...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal..."
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa..."

In [14]:
import nltk
import re 
from nltk.corpus  import stopwords

In [15]:
pip install --upgrade nltk

Requirement already satisfied: nltk in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\91979\onedrive\desktop\python.project\annaconda\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91979\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re

ps = PorterStemmer()  # instantiate the PorterStemmer
corpus = []

for i in range(0 , len(messages)):
    print(i)
    review = str(messages['title'][i])  # convert to string to avoid the error
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499
3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999
4000
4001
4002
4003
4004
4005
4006
4007
4008
4009
4010
4011
4012
4013
4014
4015
4016
4017
4018
4019
4020
4021
4022
4023
4024
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4035
4036
4037
4038
4039
4040
4041
4042
4043
4044
4045
4046
4047
4048
4049
4050
4051
4052
4053
4054
4055
4056
4057
4058
4059
4060
4061
4062
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4076
4077
4078
4079
4080
4081
4082
4083
4084
4085
4086
4087
4088
4089
4090
4091
4092
4093
4094
4095
4096
4097
4098
4099
4100
4101
4102
4103
4104
4105
4106
4107
4108
4109
4110
4111
4112
4113
4114
4115
4116
4117
4118
4119
4120
4121
4122
4123
4124
4125
4126
4127
4128
4129
4130
4131
4132
4133
4134
4135
4136
4137
4138
4139
4140
4141
4142
4143
4144
4145
4146
4147
4148
4149
4150
4151
4152
4153
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
4164
4165
4166
4167
4168
4169
4170
4171
4172
4173
4174
4175
4176
4177
4178
4179
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hillari',
 'chuck todd buzzfe donald trump polit favor breitbart',
 'news hope gop nude paul ryan emerg ayahuasca tent vision new republican parti',
 'monica lewinski clinton sex scandal set american crime stori',
 'rob reiner trump mental unstabl breitbart',
 'massachusett cop wife bust pin fake home invas robberi black live matter',
 'abort pill order rise latin american nation zika alert new york time',
 'nuke un histor treati ban nuclear weapon',
 'exclus islam state support vow shake west follow manchest terrorist massacr breitbart',
 'humili hillari tri hide camera caught min ralli',
 'andrea tantaro fox news claim retali sex harass complaint new york time',
 'hillari clinton becam hawk new york time',
 'chuck todd buzzfe eic publish fake news breitbart',
 'israel becom pivot china mid eastern calculu http journal neo org israel becom pivot china mid eastern calculu',
 'bori johnson brexit leader fumbl new york time',
 'texa oil field rebound price lull job left behind new york time',
 'bayer deal monsanto follow agribusi trend rais worri farmer new york time',
 'russia move ban jehovah wit extremist new york time',
 'still danger zone januari th',
 'open thread u elect',
 'democrat gutierrez blame chicago gun violenc nra breitbart',
 'avoid peanut avoid allergi bad strategi new york time',
 'mri show detail imag week unborn babi breitbart',
 'best kind milk dairi',
 'ryan locht drop speedo usa retail new york time',
 'one girlfriend without bastard f king ask harri',
 'conserv urg session clean obama civil right divis breitbart',
 'intern inquiri seal fate roger ail fox new york time',
 'press tv debat duff lebanon hezbollah aoun presid video',
 '',
 'samsung combust galaxi note unveil new smartphon new york time',
 'poland vow referendum migrant quota amidst eu pressur public voic heard breitbart',
 'spark inner revolut',
 'duel drill increas nato russia tension',
 'studi half car crash involv driver distract cell phone breitbart',
 'nan',
 'samantha bee explor danger rise alt right american polit video',
 'trump elect spark individu collect heal',
 'ep fade black jimmi church w laura eisenhow restor balanc video',
 'cognit true islam book review',
 'donald trump win elect biggest miracl us polit histori',
 'mind eat way fight bing new york time',
 'major potenti impact corpor tax overhaul new york time',
 'wonder glp like day elect',
 'maker world smallest machin award nobel prize chemistri new york time',
 'massiv anti trump protest union squar nyc live stream',
 'review lion bring tear lost boy wipe dri googl new york time',
 'u gener islam state chemic attack impact u forc',
 'juri find oregon standoff defend guilti feder conspiraci gun charg',
 'clinton campaign stun fbi reportedli reopen probe hillari clinton email',
 'penc speak anti abort ralli new york time',
 'berni sander say media trump gutless polit coward',
 'make briquett daili wast',
 'treason nyt vow reded report',
 'dress like woman mean new york time',
 'ella brennan still feed lead new orlean new york time',
 'press asia agenda obama tread lightli human right new york time',
 'democrat percent chanc retak senat new york time',
 'news pr disast presid panason forc resign panason tv ascend heaven without warn',
 'judg spank transgend obsess obama lie redflag news',
 'u diplomat urg strike assad syria new york time',
 'franken call independ investig trump putin crush breitbart',
 'louisiana simon bile u presidenti race tuesday even brief new york time',
 'turkey threaten open migrant land passag europ row dutch',
 'huma weiner dog hillari',
 'colin kaepernick start black panther inspir youth camp wow',
 'trump immigr polici explain new york time',
 'mari tyler moor mourn dick van dyke star new york time',
 'poison',
 'trump fan ralli across nation support presid new york time',
 'fox biz report help bash clinton ralli cover trump pack event day',
 'fiction podcast worth listen new york time',
 'mike birbiglia tip make small hollywood anywher new york time',
 'invest strategist forecast collaps timelin last gasp econom cycl come',
 'venezuela muzzl legislatur move closer one man rule new york time',
 'whether john mccain mitt romney donald trump democrat alway run war women tactic destroy republican candid',
 'breitbart news daili trump boom breitbart',
 'white hous confirm gitmo transfer obama leav offic',
 'geometri energi medit buddha',
 'poll voter heard democrat elect candid breitbart',
 'migrant confront judgment day old deport order new york time',
 'n u yale su retir plan fee new york time',
 'technocraci real reason un want control internet',
 'american driver regain appetit ga guzzler new york time',
 'hillari clinton build million war chest doubl donald trump new york time',
 'trump catch sick report snuck interview priceless respons',
 'senat contact russian govern week',
 'imag perfectli illustr struggl dakota access pipelin',
 'washington state take refuge muslim rest countri take refuge muslim breitbart',
 'houthi forc captur saudi militari base asir russia news',
 'ncaa big keep watch eye texa bathroom bill breitbart',
 'massiv espn financi subscrib loss drag disney first quarter sale breitbart',
 'megyn kelli contract set expir next year prime big show new york time',
 'teacher suspend allow student hit trump pinata cinco de mayo',
 'break trump express concern anthoni weiner illeg access classifi info month ago truthfe',
 'snap share leap debut investor doubt valu vanish new york time',
 'clinton campaign chair dinner top doj offici one day hillari benghazi hear',
 'tv seri first femal mlb pitcher can one low rate season breitbart',
 'seek best fit women final four return friday sunday new york time',
 'propos canadian nation bird ruffl feather new york time',
 'review beyonc make lemonad marit strife new york time',
 'trump ask sharp increas militari spend offici say new york time',
 'nan',
 'waterg smoke gun email discuss clean obama hillari email',
 'chapo trap hous new left wing podcast flagrant rip right stuff',
 'taiwan respond china send carrier taiwan strait new york time',
 'nan',
 'mother octob surpris hous card come tumbl',
 'explos assang pilger interview us elect expect riot hillari win',
 'telescop ate astronomi track surpass hubbl new york time',
 'close afghan pakistani border becom humanitarian crisi new york time',
 'tv anchor arriv white hous lunch donald trump breitbart',
 'pelosi republican tell trump bring dishonor presid breitbart',
 'beauti prehistor world earth wasteland',
 'ignor trump news week learn new york time',
 'donald trump unveil plan famili bid women vote new york time',
 'eu finland help settlement syria conflict iran parliament speaker',
 'fbi director comey leak memo explain reopen clinton email case',
 'montana democrat vote bill ban sharia law call repugn breitbart',
 'monsanto tribun go happen',
 'shame heartbreak anoth day america',
 'offici simon bile world best gymnast new york time',
 'nan',
 'liter hurt brain read econom idioci emit trumpkin libertarian',
 'gorafi magazin entretien exclusif avec barack obama plu rien secouer merdez vou le gorafi',
 'u n secretari gener complain mass reject global favor nation',
 'trump bollywood ad meant sway indian american voter hilari fail video',
 'fbi find previous unseen hillari clinton email weiner laptop',
 'year american journalist kill conspiraci theori syria proven fact',
 'report illeg alien forego food stamp stay trump radar',
 'make netherland great hahaha spread worldwid',
 'four kill injur jerusalem truck ram terror attack',
 'leader salut comrad newt brutal megyn sic kelli beatdown play game',
 'student black colleg got beaten mace protest kkk david duke',
 'despit strict gun control one child youth shot everi day ontario',
 'rise internet fan bulli new york time',
 'newli vibrant washington fear trump drain cultur new york time',
 'fed hold interest rate steadi plan slower increas new york time',
 'battl unesco',
 'latest test white hous pull easter egg roll new york time',
 'burlesqu dancer fire investig secret servic trump assassin tweet breitbart',
 'clinton haiti',
 'cuomo christi parallel path top troubl got new york time',
 'top place world allow visit',
 'new studi link fluorid consumpt hypothyroid weight gain wors',
 'jame matti secretari offens',
 'black church burn spray paint vote trump',
 'sear agre sell craftsman stanley black amp decker rais cash new york time',
 'takata chief execut resign financi pressur mount new york time',
 'goodby good black sabbath new york time',
 'teen geisha doll gang bust arm robberi breitbart',
 'mohamad khwei anoth virginia man palestinian american muslim charg terror',
 'rememb talk stand rock',
 'price obamacar replac nobodi wors financi breitbart',
 'va fail properli examin thousand veteran',
 'trump famili alreadi sworn secreci fake moon land soon',
 'sport writer nfl great jim brown decad civil right work eras say nice thing donald trump breitbart',
 'spider pig found amazon rain forest',
 'watch tv excus republican skip donald trump convent new york time',
 'open letter trump voter told like',
 'comment power corpor lobbi quietli back hillari nobodi talk runsinquicksand',
 'teacher unsur get smash eighth night run',
 'hijack end peac libyan airlin land malta new york time',
 'like girl girl geniu new york time',
 'scientist say canadian bacteria fossil may earth oldest new york time',
 'pro govern forc advanc syria amid talk u russia cooper new york time',
 'cancer agenc fire withhold carcinogen glyphos document',
 'work walk minut work new york time',
 'milit use toxic ga near aleppo airport report',
 'steve harvey talk hous presid elect trump new york time',
 'coalit u troop fight mosul offens come fire',
 'uk citizen war hero get cheap pre fab hous muslim colon get taxpay fund luxuri council home',
 'vet fight war fed demand money back illeg refuge keep money',
 'mr trump wild ride new york time',
 'fbi director comey bamboozl doj congress clinton',
 'food natur unclog arteri prevent heart attack',
 'death two state solut',
 'watch polic vicious attack arrest peac protest dapl includ children elderli',
 'nan',
 'comment parent date asleep car cop arriv kill facespac',
 'could teach men nurtur counteract cultur toxic masculin',
 'donald trump team show sign post elect moder new york time',
 'miami beach tri tame raucou street fishbowl drink stay new york time',
 'doctor mysteri found dead summit breakthrough cure cancer',
 'donald trump unsink candid new york time',
 'shock new mock hillari ad campaign warn take us war enlistforh fightforh dieforh',
 'failur us democraci',
 'exclus famili slain border patrol agent brian terri say eric holder among real crimin respons',
 'trump tell report wall work ask israel breitbart',
 'america surviv next year',
 'commission start press cleveland indian logo new york time',
 'babylon mysteri religion seri',
 'un plan implant everyon biometr id drill',
 'trump attack senat credibl gorsuch comment new york time',
 'clinton advisor lose leak email hillari illeg activ',
 'art laffer paul ryan perfect right breitbart',
 'donald trump blame econom crash',
 'new world order push back brexit revolut',
 'pokemon go player inadvert stop peopl commit suicid japan',
 'california senat race tale divers flail g p new york time',
 'exclus sourc say megyn kelli would welcom back fox news',
 'break preced obama envoy deni extens past inaugur day new york time',
 'brexit vote go monti python may offer clue new york time',
 'blind mystic predict bad news trump',
 'total vet fail left wing snowden fan girl realiti winner get access nsa secret',
 'nan',
 'somalia u escal shadow war new york time',
 'free care bless victim orlando nightclub attack new york time',
 'durabl democrat counti countri could go trump',
 'fed challeng rais rate may existenti new york time',
 'russia intent attack anyon absurd say vladimir putin',
 '',
 'f investig errant flight involv harrison ford new york time',
 'ask holli everyon problem',
 'fed rais key interest rate cite strengthen economi new york time',
 'la expresi n lo siguient ya es la utilizada lo siguient en el castellano',
 'trump berat news media new strategi need cover new york time',
 'sunk cost billion wast imaginari weapon sinc',
 'chang montenegrin leader chang ideolog',
 'u drone strike target taliban leader new york time',
 'u intellig expect al qaeda attack monday new york virginia texa',
 'told cannabi great revers alzheim',
 'report megyn kelli kick nbc show kardashian famili interview',
 'local percent may rich think new york time',
 'dr david duke mark collett uk collett explain duke trump victori would chang polit forev',
 'statement senat well fargo chief deepli sorri new york time',
 'cnn statement distanc network buzzfe fake news dossier breitbart',
 'c e ponder new game trump rule new york time',
 'spicer bradi stolen jersey anoth bad press breitbart',
 'scaredi cat investig peopl enjoy fear new york time',
 'left vision',
 'showdown loom u question chines deal german chip design new york time',
 'fbi obtain warrant search huma abedin email',
 'trump administr take harder tack trade china new york time',
 'pew american trust level feder govern plummet histor low breitbart',
 'islam state support former nation guardsman plead guilti terror charg virginia',
 'western qld drover show solidar c u b worker drink sauv blanc betoota advoc',
 'spicer report go rais hand like big boy girl breitbart',
 'leader applaud gorsuch confirm win pro life movement',
 'newstick',
 'french vogu march cover featur transgend model new york time',
 'trump veer parti line gun control new york time',
 'oligarchi prepar groundwork steal elect',
 'ya hay reencuentro de operaci n triunfo que edicion de operaci n triunfo',
 'chatsworth hous tale five centuri new york time',
 'uncomfort love affair donald trump new england patriot new york time',
 'john mccain withdraw support donald trump disclosur record new york time',
 'strang unend limbo egypt hosni mubarak new york time',
 'poverti rose u hous district obama presid',
 'huma abedin seek fbi immun deal',
 'singl mom escap friend zone one non date time new york time',
 'boe suit futur spaceflight new spacesuit design breitbart',
 'trump float oliv branch might keep part health law new york time',
 'wapo tri compar elizabeth warren break senat rule milo shut violent riot breitbart',
 'crumpl school bu leav chattanooga daze new york time',
 'die came back life incred messag human',
 'fight nation african american museum new york time',
 'father manchest suicid bomber arrest libya breitbart',
 'secret true leader',
 'muslim demand local walk dog public violat sharia disrespect',
 'hillari campaign bed pac staff donat k fbi agent wife investig',
 'still tri flip elector colleg block trump win',
 'al sharpton dem point appeal archi bunker trump voter breitbart',
 'think mani doom sayer trump get offic',
 'democrat jump session resign band wagon breitbart',
 'russia turkey share intellig data',
 'alt right architect glenn beck open fire alt right grave threat republ audio tweet',
 'politic justic protect hillari',
 'north carolina satur surpris reel hurrican matthew new york time',
 'live love submit memori new york time',
 'nan',
 'achiev mind work medit cushion requir new york time',
 'world first zero emiss hydrogen power passeng train unveil germani',
 'confus chip credit card get line new york time',
 'britain send hundr soldier tank estonia biggest militari deploy sinc cold war',
 'brook trump side foreign leader us presid israel russia breitbart',
 'toxic air home get rid natur',
 'connecticut reader report record voter registr inspir trump',
 'germani react merkel trump visit could lot wors new york time',
 'justin rose outduel henrik stenson golf gold medal new york time',
 'iceland water cure new york time',
 'us hold cyberwar russia elect jason ditz',
 'shorten l train shutdown month new york time',
 'time presid decid new york time',
 'u n relief offici call crisi aleppo apex horror new york time',
 'berkeley treat violent anti speech left like kkk',
 'statist propaganda mani syrian us regim chang kill',
 'self help guru jame altuch own thing new york time',
 'trump religi liberti order give session major leeway breitbart',
 'demoledor amparo contra salgado keiko congresista',
 'era trump china presid champion econom global new york time',
 'sad saga john walker lindh rebel without clue',
 'court disagre michigan vote recount new york time',
 'berni sander feud democrat leadership heat new york time',
 'shortest power explan trump victori ever seen',
 'russia look popul far east wimp need appli new york time',
 'johnson amend trump vow destroy explain new york time',
 'donald trump march life full support',
 'polic offici found dead long island suicid suspect new york time',
 'life love enamel pin love etsi shop care enamel pin explod pictur bulldog puppi lose shit amaz look pizza find someth',
 'nevada rep elect worker intimid',
 'radic chang store world global market readi',
 'like make showbiz best friend new york time',
 'trump nomin neil gorsuch suprem court new york time',
 'spark fli biker trump meet protest',
 'bidder cast doubt serious mexican border wall project',
 'stake us elect',
 'israel approv addit fund settlement west bank new york time',
 'tx gov abbott sign legisl could put sheriff sanctuari citi jail breitbart',
 'donald trump hold thank ralli cincinnati announc pick defens secretari new york time',
 'lawmak look bipartisanship health care new york time',
 'insid conserv push state amend constitut new york time',
 'donald trump tell n r hillari clinton want let violent crimin go free new york time',
 'pope franci trump japan tuesday brief new york time',
 'mayorsstand day tout support illeg immigr',
 'trump campaign celebr',
 'democrat drag jeff session confirm fight breitbart',
 'break news podesta brother pedo ring mr trump drain swamp v guerrilla economist',
 'la frase destacada del debat de investidura',
 'confus jihad hirabah build peac world',
 'lazi liber journalist smear bannon',
 'australia close detent center manu island still accept asylum seeker new york time',
 'politico hillari clinton run breitbart',
 'giant lynx make ador sound whenev human rub face',
 'minnesota cop found guilti philando castil shoot trial',
 'million american kill minut',
 'wayn madsen cia alway serv interest wall street',
 'novemb daili contrarian read',
 'flashback report obama campaign rep talk iran hama',
 'lesseroftwoevil',
 'anoth power earthquak strike central itali',
 'aya cash first time ate veget new york time',
 'trump advis say isra settlement illeg',
 'serena william prevail open problem new york time',
 'soul man sam moor honor perform trump inaugur',
 'ferrel came back bush destroy trump video',

In [19]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
print(onehot_repr)

[[4054, 4332, 4432, 4538, 801, 3140, 428, 2666, 713, 1639], [2988, 2500, 4371, 3209, 1696, 3131, 4100], [1984, 1662, 3165, 2773], [902, 2262, 2660, 1625, 612, 880], [1776, 1696, 3508, 397, 2523, 4261, 1696, 997, 3820, 2329], [1951, 3790, 1658, 3279, 2748, 4043, 4883, 2724, 3573, 67, 146, 1511, 1404, 4695, 4100], [2181, 2181, 2942, 1770, 4001, 4037, 4978, 4403, 1884, 1589, 8, 684], [1799, 546, 1766, 371, 2791, 4805, 4756, 4059, 255, 1864, 200], [4710, 1447, 2299, 2835, 4043, 4122, 386, 3604, 4907, 3172, 255, 1864, 200], [4068, 4652, 4367, 304, 2711, 3170, 4043, 3987, 255, 1864, 200], [1504, 4544, 3215, 1493, 910, 767, 4285, 2383, 4043, 470], [3821, 180, 2927, 139, 596, 20, 257, 2809], [2671, 766, 609, 1546, 4780, 3190, 1034, 37, 1917, 771, 3154], [1625, 3166, 801, 767, 4043, 2711], [817, 2777, 4276, 1460, 4288, 431, 1688, 130, 680], [2694, 3129, 2864, 2411, 2905, 4958, 3352, 255, 1864, 200], [2545, 2571, 1081, 4711, 3320, 255, 1864, 200], [4027, 2966, 1110, 817, 2722, 483, 1930, 3894, 1983, 4721], [1248, 201, 2500], [1033, 1638, 3796, 2835, 4043, 3565, 4023, 4100], [451, 895, 3019, 1490, 960, 147, 3081, 1580, 2608, 2264, 255, 731, 4805], [2386, 2611, 4371, 4823, 473, 4012, 2466, 697, 4261], [2243, 4851, 4043, 3912, 2215, 4100], [148, 3960, 1298, 987, 2882, 2771, 4958, 4478, 1177, 3604, 2453, 1834], [492, 4834, 1880, 4849, 3658, 2466, 4969, 4219, 4067, 255, 1864, 200], [1290, 1906, 3509, 1683, 1238, 2941, 4910], [1404, 1133, 4300, 4357, 3691, 3123, 464, 1171, 3307, 281, 2984, 4100], [1577, 2500, 480, 4765, 2214, 4071, 1137, 4398], [780, 1389, 2388, 451, 503, 1885, 4823, 360, 3765, 255, 1864, 200], [2500, 4371, 3791, 3858, 255, 1864, 200], [1033, 1638, 3796, 4491, 939, 2771, 451, 4100], [3749, 4637, 3977, 1781, 3197, 1811, 568, 2033, 4493, 267, 1429, 3749, 4637, 3977, 1781, 3197, 1811, 568], [2725, 1730, 1650, 3189, 956, 255, 1864, 200], [4255, 47, 3908, 218, 2730, 1936, 3272, 1051, 29, 255, 1864, 200], [4963, 1580, 4895, 1171, 4249, 4376, 3663, 2951, 4909, 255, 1864, 200], [2711, 1465, 1238, 383, 1209, 4307, 255, 1864, 200], [2543, 2516, 3731, 1467, 3473], [3010, 1647, 1731, 88], [4948, 570, 1416, 1462, 1374, 930, 633, 4100], [4750, 1751, 4750, 1986, 1161, 1965, 255, 1864, 200], [78, 4332, 1843, 3322, 4463, 1684, 2020, 4100], [2178, 322, 2000, 4772], [147, 2788, 422, 1335, 371, 3020, 255, 1864, 200], [2242, 2494, 4494, 337, 208, 3544, 4133, 2805], [2193, 2827, 4438, 3941, 1504, 2972, 4556, 1535, 4100], [537, 762, 3037, 976, 2297, 538, 2388, 255, 1864, 200], [4945, 3272, 2347, 3152, 926, 774, 2853, 135, 4695], [], [1377, 2705, 2276, 4349, 2884, 255, 1052, 255, 1864, 200], [2224, 3691, 1338, 1770, 315, 4762, 2078, 1066, 1340, 3385, 3326, 4100], [405, 3659, 4419], [3461, 57, 3203, 1275, 2711, 4471], [4977, 4743, 4528, 4620, 3584, 3720, 3715, 4377, 3314, 4100], [2280], [1015, 2531, 3347, 2516, 4849, 4002, 4556, 2466, 3565, 4695], [4043, 88, 405, 2861, 1389, 3949], [3776, 4919, 3604, 4797, 4907, 3514, 240, 1352, 1169, 3167, 4695], [208, 4569, 1133, 3325, 1942], [2835, 4043, 1766, 88, 768, 488, 1625, 3565, 3213], [4609, 2335, 1760, 479, 996, 255, 1864, 200], [2694, 704, 411, 2699, 4322, 2817, 255, 1864, 200], [4326, 3232, 4523, 448, 88], [713, 3546, 4494, 3093, 1891, 313, 2152, 2959, 255, 1864, 200], [3297, 1228, 4043, 2460, 2245, 284, 783, 2453, 3507], [1942, 2204, 3050, 3745, 2121, 266, 3904, 4351, 1478, 255, 1864, 200], [1731, 1923, 1133, 4300, 4235, 537, 411, 1731, 578], [1348, 2905, 1084, 3255, 1985, 4530, 2023, 3118, 1374, 2724], [4371, 3647, 1349, 1248, 338, 2224, 2514, 2500, 4371, 2366], [3901, 2050, 1228, 492, 4398, 255, 1864, 200], [263, 4119, 4213, 431, 4043, 4827, 3565, 4623], [4995, 4457, 3462, 4140], [1833, 2110, 3691, 948, 829], [2769, 4523, 1696, 2343, 255, 1864, 200], [4585, 2383, 2543, 17, 2794, 255, 4968, 255, 1864, 200], [4945, 4361, 470, 1504, 4562, 2423, 4408, 4556, 255, 1864, 200], [4948, 3213, 455, 4332, 2566, 255, 1864, 200], [451, 2008, 133, 135, 3499, 578, 2485, 3499, 3272, 152, 1784, 4494, 4308], [2408, 4977, 643, 4338, 1504, 2620, 2214, 451], [1731, 4574, 2827, 1307, 3319, 313, 255, 1864, 200], [855, 2800, 8, 321, 4043, 1242, 1675, 4100], [1701, 4570, 1895, 1731, 4756, 4823, 1426, 4538, 2771, 255, 1864, 200], [1962, 1237, 3010, 1770, 4624, 274, 2120, 4880, 1599], [3489, 38, 2342, 2500], [3221, 1156, 1057, 3604, 4395, 2623, 984, 3400, 2320], [4043, 347, 3243, 2878, 255, 1864, 200], [2245, 1984, 2662, 1788, 3784, 4019, 4161, 957, 255, 1864, 200], [645], [4043, 3783, 4398, 296, 4969, 4357, 135, 255, 1864, 200], [2388, 3833, 829, 2765, 1723, 4371, 4398, 506, 4043, 4169, 4144, 448], [397, 715, 4846, 4743, 255, 1864, 200], [3458, 3883, 453, 4995, 3340, 1658, 223, 255, 1864, 200], [1978, 1871, 1016, 1581, 1364, 4343, 31, 2579, 4102, 3199], [4678, 3108, 2070, 1465, 3050, 2242, 312, 2124, 255, 1864, 200], [2492, 4001, 1487, 2003, 3420, 2835, 4043, 4948, 2061, 1172, 2827, 3067, 514, 3158, 731, 4340], [4100, 451, 3462, 4043, 2202, 4100], [3460, 4054, 1998, 3794, 1, 1504, 1088, 465], [1670, 1396, 1517, 213], [4537, 2644, 3326, 4948, 88, 4340, 4100], [1770, 2330, 3383, 448, 2225, 2939, 1880, 255, 1864, 200], [3135, 1731, 1144, 4712, 4045, 4367, 4294, 255, 1864, 200], [4508, 139, 1934, 1906, 3010, 2027, 992], [2466, 3720, 4012, 2736, 1432, 1674, 255, 1864, 200], [2500, 4371, 3417, 817, 2827, 2223, 365, 2835, 4043, 255, 1864, 200], [4043, 1831, 967, 829, 4530, 449, 1991, 2521], [2566, 2527, 2671, 4276, 4463], [3322, 3420, 659, 2631, 3894, 1983, 4721], [1782, 4300, 1422, 4184, 4942, 2853, 4030, 1422, 4184, 4942, 4100], [2557, 578, 917, 597, 3190, 1034, 1377, 2711, 451], [1387, 3209, 4882, 4688, 868, 4255, 1511, 2759, 4100], [3297, 717, 2939, 3590, 4127, 935, 2239, 1493, 2642, 2901, 4100], [2302, 3845, 3324, 4012, 92, 4496, 3500, 2281, 3209, 4332, 255, 1864, 200], [2813, 2097, 4875, 3357, 1978, 4043, 1814, 1665, 3746, 743], [533, 4043, 1922, 202, 260, 38, 3638, 1983, 989, 2365, 570, 4796, 4879], [767, 3275, 348, 2096, 2502, 2108, 4278, 660, 255, 1864, 200], [4371, 3647, 2229, 4964, 4437, 1242, 3166, 2242, 448, 2500, 4933, 178], [3272, 134, 1493, 633, 1148, 2992, 4625, 2242, 4863, 203, 914, 4100], [2197, 2178, 1930, 3067, 304, 3731, 1971, 3290, 1688, 255, 1864, 200], [1604, 4577, 4969, 591, 3618, 1585, 255, 1864, 200], [1942, 4707, 4995, 970, 1417, 352, 255, 1864, 200], [4043, 4133, 2017, 3203, 3190, 4464, 3166, 4213, 255, 1864, 200], [2280], [403, 4902, 1374, 2366, 952, 3941, 1504, 2500, 2366], [3383, 4381, 4054, 255, 1051, 206, 715, 1522, 2152, 4556, 2012], [4632, 3374, 1781, 1256, 3581, 4632, 4877, 255, 1864, 200], [2280], [2074, 727, 930, 4054, 3754, 3199, 837], [252, 2793, 649, 449, 1625, 88, 7, 2612, 2500, 1766], [466, 1184, 2159, 4311, 1335, 1475, 255, 1864, 200], [201, 3810, 3340, 4355, 4637, 4997, 2447, 255, 1864, 200], [3272, 930, 3684, 3460, 4054, 4233, 2835, 4043, 4100], [1387, 731, 2103, 4043, 3050, 391, 135, 4100], [2683, 265, 3546, 14, 2681], [1361, 4043, 451, 4463, 4743, 255, 1864, 200], [2835, 4043, 2884, 4367, 3305, 1477, 3067, 2685, 255, 1864, 200], [2078, 4289, 2765, 2123, 313, 3382, 89, 2178, 3028], [1248, 4645, 3140, 2891, 1161, 2878, 2224, 4371, 2366, 3745], [4956, 4948, 2685, 2759, 1238, 3187, 2031, 2800, 1276, 4100], [4895, 638, 2513, 854], [3997, 1440, 3507, 448, 2565], [3166, 4570, 1895, 3546, 2178, 4851, 255, 1864, 200], [2280], [3515, 336, 678, 1231, 2579, 3870, 3274, 2096, 216], [3289, 3336, 748, 1522, 3722, 1372, 1504, 3371, 3503, 1239, 3596, 1928, 1828, 3289], [1731, 3135, 1824, 1923, 1550, 3849, 332, 3163, 4023, 4969], [4043, 120, 824, 696, 4424, 4014, 2466, 2644, 2081, 3384, 4695], [1248, 2905, 410, 4687, 2500, 4371, 2366, 38, 4080], [3500, 2466, 3471, 2262, 3118, 1186, 313, 3050, 4699], [829, 3638, 3030, 2376, 4562, 1827, 229, 4043, 886], [4995, 2003, 2001, 814, 1943, 2807], [3731, 2262, 689, 2384, 1570, 685, 866, 537], [3189, 903, 4317, 4249, 1921, 2302, 2195, 3845, 1392, 3821, 971], [3357, 3604, 904, 323, 402, 3942, 2460, 2507, 2299, 1563], [361, 3143, 1374, 2027, 2242, 1965, 984, 164, 3889, 448, 3004], [4849, 992, 3783, 4357, 255, 1864, 200], [472, 1134, 1782, 2372, 4043, 1848, 598, 255, 1864, 200], [446, 1478, 703, 203, 4752, 4367, 1017, 3203, 255, 1864, 200], [1944, 423], [1052, 686, 3460, 4054, 2917, 3418, 43, 3839, 255, 1864, 200], [1778, 3442, 2773, 321, 1546, 673, 4043, 2835, 1639, 4100], [4371, 3561], [2608, 2168, 3957, 2395, 4437, 305, 323, 255, 1864, 200], [4437, 1106, 3546, 4875, 1990], [255, 4977, 767, 1949, 4585, 3686, 4216, 2119, 327], [351, 3227, 1824, 963], [3604, 4907, 248, 4712, 758, 2685, 4043], [2789, 923, 3232, 1637, 3385, 3604, 848, 1630, 3663, 3344, 255, 1864, 200], [1721, 1081, 384, 2485, 2939, 1066, 4558, 255, 1864, 200], [1192, 51, 3604, 4310, 255, 1864, 200], [501, 4550, 2863, 1161, 987, 4744, 1177, 4100], [2186, 2537, 3507, 3505, 312, 281, 2466, 4942, 2724, 866], [3161, 838, 1430, 2506], [2730, 733, 906, 3211, 327, 2939, 4100], [4764, 3384, 3819, 1331, 320, 2292], [4043, 3305, 2592, 1065, 1213, 2771, 1831, 4624, 2130], [4707, 4536, 1082, 2001, 3948, 2480, 4233, 2972, 4556, 551, 4952, 4213, 2809, 4485, 2835, 4043, 4100], [3493, 1642, 3166, 2366, 2406, 2924], [4688, 3272, 3773, 731, 3952, 2835, 4043, 2751, 255, 1864, 200], [3010, 428, 4043, 2644, 137, 4523], [3229, 2444, 2699, 1756, 2926, 4068, 2500, 3211, 838, 3066], [2813, 3921, 3165, 2824, 2544, 4209, 1172], [4187, 4983, 2592, 2813, 3820, 4624, 1183, 255, 1864, 200], [4523, 2834, 2834, 4256, 255, 1864, 200], [3260, 4213, 4577, 4449, 169, 1968, 14, 504, 255, 1864, 200], [3492, 4276, 578, 3787, 313, 294, 838, 1731, 2711, 142, 255, 1864, 200], [4993, 43, 2773, 1440, 3321, 1332, 2712], [551, 4073, 3898, 551, 255, 1864, 200], [3933, 1953, 4069, 1432, 4850, 2888, 225, 829], [341, 3979, 838, 4054, 135, 88, 4043, 255, 1864, 200], [17, 1731, 1498, 479, 2857, 963, 3199, 2773], [3590, 3684, 2827, 3284, 3165, 1717, 486, 631, 4054, 4942, 4498, 3165, 1163, 3917, 2942, 687, 4958], [424, 479, 2827, 446, 4830, 3118, 4068, 3638, 4184, 4882, 3118], [2694, 4043, 3383, 1467, 255, 1864, 200], [1248, 4645, 3140, 714, 1242, 1963, 4371], [4562, 1079, 4822, 336, 899, 2531, 537], [3820, 2242, 4300, 618], [4688, 4044, 2202, 537, 1930, 2592, 2460, 2959, 1587, 541, 2962], [2280], [3229, 959, 1096, 1270, 4528, 3960, 3684, 2262, 1719], [4679, 3462, 492, 2669, 2099, 598, 4069, 2835], [2835, 4043, 3176, 4332, 2410, 958, 88, 1658, 255, 1864, 200], [3302, 463, 480, 4049, 2716, 1425, 2716, 861, 229, 255, 1864, 200], [3972, 2663, 3166, 1370, 2998, 1919, 2451, 4993], [2835, 4043, 4580, 4340, 255, 1864, 200], [3296, 255, 4333, 2500, 824, 3647, 4308, 1422, 1625, 2827, 1520, 1975, 2627], [881, 1625, 3325], [1404, 3305, 2358, 4355, 1797, 3639, 181, 3302, 4213, 2001, 1471, 2069, 139, 1438, 2521], [4043, 2103, 829, 3637, 551, 4133, 3749, 4100], [2565, 313, 4496, 3500], [2248, 1057, 4945, 2624, 4014, 2910, 255, 1864, 200], [3919, 2663, 2179, 134], [1906, 4367, 604, 483, 658, 3021, 57], [4043, 537, 2566, 3539, 4088, 3229, 255, 1864, 200], [4371, 3621, 858, 2891, 2366, 2500, 3638, 264], [1148, 18, 960, 147, 4064, 4556, 4100], [2835, 4043, 1416, 2579, 4620], [255, 3546, 1880, 1943, 4068, 1650, 4419], [4506, 2513, 1806, 2887, 2395, 4683, 242, 4099, 2905], [1711, 2566, 4823, 1341, 4787, 4165, 3581, 3443, 255, 1864, 200], [1404, 4591, 4213, 2302, 3845, 3279, 241, 4068, 2388, 451], [533, 4350, 1504, 4635, 2494, 2059, 161, 151, 448, 255, 1864, 200], [1650, 2685, 2513, 2385, 3227, 1968, 2127, 4785, 255, 1864, 200], [1987, 1350, 4223, 1161, 451, 4043], [1344, 424, 3384, 1051, 206, 873, 3783, 2834, 2992, 3760, 3165, 1983, 1687, 1546], [2280], [2674, 1731, 4935, 1792, 2827, 255, 1864, 200], [2035, 294, 3202, 3016, 685, 3025, 537, 255, 1864, 200], [2274, 4948, 4992, 4030, 4679, 2513, 4043], [446, 4023, 3663, 203, 1968, 3589, 255, 1864, 200], [2711, 1830, 537, 2528, 1600, 4213, 4524, 1242], [], [208, 321, 1902, 684, 3584, 1073, 1286, 255, 1864, 200], [4133, 669, 483, 2296], [446, 3663, 1017, 703, 203, 3349, 2743, 1571, 255, 1864, 200], [676, 4292, 3135, 2484, 3747, 671, 1146, 676, 1382, 2484, 3747, 1045, 1471, 4125], [4043, 1420, 451, 431, 255, 1965, 2296, 506, 255, 1864, 200], [1103, 3369, 217, 4140, 2237, 4910, 3154], [1320, 1028, 3189, 1320, 4103], [1731, 3866, 1307, 4815, 1404, 3189, 255, 1864, 200], [1731, 3483, 7, 2625, 1967, 537, 255, 255, 1864, 3505, 4255], [137, 4178, 2001, 891, 4607], [829, 2302, 3845, 3762, 88, 4332, 631, 3305, 449], [2428, 3213, 1968, 96, 1047, 255, 1864, 200], [1861, 2299, 1563, 1144, 1396, 3590, 1396, 2878, 1563, 4043, 1219, 3279, 1320, 3565, 3979], [3868, 2566, 2545, 2571, 1081, 1534, 3652, 255, 1864, 200], [2969, 3868, 4083, 3675, 3796, 2771, 451, 4498, 4100], [1100, 3606, 1973, 255, 971, 4043, 2124, 255, 1864, 200], [3216, 4209, 4087, 4856, 3507, 1161, 4945, 4100], [1511, 4880, 321, 4683, 4574, 2372, 255, 1864, 200], [1051, 2264], [3647, 4845, 1731, 111, 2015, 1580, 4616, 1209, 3906, 255, 1864, 200], [1248, 3657, 1446, 1302, 3489, 1559, 2366], [4043, 1413, 1422, 2204, 2677, 4231, 1781, 255, 1864, 200], [1777, 2466, 4740, 1980, 2023, 4276, 1776, 3509, 4863, 4100], [1133, 4300, 4357, 2514, 4969, 787, 3592, 4530, 866, 2724, 3505], [2735, 315, 4271, 4332, 361, 1100, 1731, 2443, 4334, 861, 4073, 627, 2393, 103], [3216, 829, 2513, 3663, 4583, 4523, 3209, 266, 2834, 4100], [3189, 2448, 4088, 1998, 1766, 3492, 2181, 414], [670], [371, 4643, 4107, 506, 3642, 643, 3902, 255, 1864, 200], [4043, 4578, 4805, 4990, 1374, 2027, 255, 1864, 200], [2948, 4706, 1227, 116, 88], [671, 2650, 620, 3746, 2700, 3135, 760, 1003, 3995, 3746, 2700, 3135, 760], [2280, 4054, 1341, 4699, 4262, 255, 1864, 200], [4029, 2748, 2932, 2835, 4043, 255, 1788, 1932, 255, 1864, 200], [4001, 1487, 233, 4357, 2835, 4043, 4460, 845, 255, 1864, 200], [2035, 1628, 3623, 774, 3373, 3289, 255, 1864, 200], [1495, 2122, 1731, 4054, 1108, 1504, 135], [3489, 1559, 2197, 1248, 3086, 1580], [2660, 3358, 1429, 1291, 3731, 2242, 16, 1096, 200, 255, 1864, 200], [3273, 1899, 192, 4788, 255, 3137, 3906, 4100], [4043, 546, 973, 3281, 1662, 4882, 3169, 1683, 2031, 255, 1864, 200], [3064, 480, 1328, 366, 4421, 533, 2566, 2124, 1388, 2174, 4227, 2612, 4100], [3159, 4425, 3696, 1088, 3237, 2794, 255, 1864, 200], [760, 1400, 4068, 2181, 570, 4494, 4408], [479, 4969, 4001, 2466, 1761, 255, 1864, 200], [1381, 3307, 4099, 2486, 1930, 2260, 4100], [1546, 4569, 3189], [4942, 4830, 2428, 4073, 2342, 1340, 2064, 3187, 1278], [2500, 3647, 2848, 2242, 997, 1194, 1875, 1248, 3639, 1298, 321], [2543, 480, 1155, 731, 904, 2604, 4043, 1766], [2625, 1244, 4332, 1765, 3482, 3685, 2265, 4043, 2644, 4100], [1047, 4113, 1913, 63, 4043, 3165, 465], [4948, 2310, 4438, 2485, 2291, 963, 4100], [2711, 1962, 3275, 3483, 3427], [4002, 4556, 4085, 1438, 1927, 3010, 2773, 4002, 4556, 2870, 1672, 2266, 3802, 1639], [3856, 2393, 48, 2500], [2724, 201, 2154, 930, 1005, 2089, 1854, 255, 1864, 200], [2453, 2748, 1745, 3311, 255, 1864, 200], [2280], [1166, 4609, 551, 1517, 3017, 4185, 255, 1864, 200], [3546, 1493, 1550, 3198, 1995, 2444, 1786, 3950, 2884, 2688], [4419, 1209, 3685, 3754, 3165, 4990, 255, 1864, 200], [129, 1256, 3120, 665, 2471, 1965, 768, 3190, 1420, 3154, 1053, 2827], [809, 4043, 1997, 2451, 3189, 1625, 135, 3749, 2711, 4100], [4069, 4559, 4958, 3165, 1294, 1079], [2267, 251, 829, 845, 2644, 2434, 2623, 4043], [2688, 1496, 3954, 4043, 1990, 4679, 3057, 327, 255, 1864, 200], [3499, 2122, 4592, 2888, 1386, 4468, 3104, 2197, 255, 1864, 200], [4564, 464, 2451, 255, 1864, 200], [1625, 1478, 1795, 2711, 88, 2666, 3593], [1667, 1612, 3950, 2338, 570, 255, 1864, 200], [200, 135, 2490, 255, 1864, 200], [1731, 3135, 2831, 3166, 2800, 2447, 2888, 2642, 748, 255, 1864, 200], [170, 2374, 4227, 1228, 35, 1051, 4523, 2507], [730, 3716, 4113, 1896, 1625, 535, 1320, 2262], [3892, 2765, 2231, 351, 4059, 4950, 4485, 255, 1864, 200], [4043, 2672, 1449, 1880, 4211, 4438, 2694, 4480, 4100], [2353, 4010, 4740, 1192, 4346, 2803], [4337, 4043, 1781, 135, 4266, 2579, 3163, 255, 1864, 200], [2912, 4255, 4001, 1545, 451, 1305, 4494, 4785], [339, 4108, 927, 2685, 1167, 255, 1864, 200], [263, 4119, 2657, 4948, 4398, 4001, 255, 1864, 200], [3807, 2444, 1963, 4043, 1219, 4272, 4037], [2711, 4207, 4804, 580, 1146, 947, 2296, 2868, 255, 1864, 200], [1730, 1084, 4043, 3691, 3158, 2878, 255, 1864, 200], [2835, 4043, 4107, 2181, 2145, 4357], [4044, 3166, 3166, 1370, 1589, 355, 4099, 4932, 255, 1864, 200], [2181, 2748, 3728, 2882, 2748, 987, 2710, 294, 3728, 2882, 36, 4403, 325, 4742, 858, 4873, 1712, 4207, 4662, 2905, 3198], [3661, 1717, 88, 4334, 2461], [2385, 1320, 547, 3546, 3163, 1431, 2544], [4523, 4995, 4797, 2178, 1291, 255, 1864, 200], [4043, 4059, 3008, 4088, 2613, 339, 255, 1864, 200], [405, 975, 4300, 4043, 376, 2460], [1984, 3836, 2108, 4981, 606, 4355, 3637, 2935], [1322, 1625, 88], [3749, 377, 1494, 3917, 2123, 464, 4959, 255, 1864, 200], [952, 368, 613, 2410, 2319, 4679, 2283, 3516, 1926, 452, 3508, 4100], [2835, 4043, 1478, 1258, 4398, 3959, 3178, 3530, 4303, 1824, 255, 1864, 200], [1674, 4207, 1509, 1683, 294, 255, 1864, 200], [4728, 2193, 1943, 4300, 1084, 4180, 255, 1864, 200], [2835, 4043, 2103, 3135, 305, 2500, 4371, 3010, 4393, 4227, 1438, 2513, 2035, 255, 1864, 200], [3643, 1929, 4043, 2905, 1426, 2771, 255, 1864, 200], [4232, 448, 4434, 4357, 3638, 347], [4043, 3647, 316], [4948, 935, 4669, 4438, 1998, 479, 4100], [533, 451, 2438, 2135, 4346, 2045, 2694, 4043, 1848, 415, 2936, 1862, 669], [676, 24, 1475, 1324, 2347, 3746, 820], [4419, 4743, 1153, 3417, 2592, 3546], [2156, 2685, 3471, 1379, 2995], [4935, 201, 1859, 1995, 2300, 355, 2543, 3144, 2430, 4863, 255, 1864, 200], [921, 2500, 4371, 1172, 4100], [4387, 397, 4995, 15, 3124, 3376, 4408, 1536, 3959], [4657, 3960, 3166, 4530, 3384, 881, 186, 202], [817, 2466, 2262, 3898], [2996, 4256, 2212, 2061, 1534, 703, 3637, 1425], [2515, 3462, 3074, 1231], [1782, 829, 1504, 3647, 1717, 838, 89, 1690], [4601], [3507, 2444, 4021, 1307, 926, 3737], [3142, 3344, 1493, 200, 1184, 4249, 255, 1864, 200], [4043, 909, 4213, 2969, 2123, 3638], [440, 3560, 1227, 3010, 2296, 255, 1864, 200], [4698, 312, 2196, 2662, 780, 957, 4043, 151], [4168, 1400, 4068, 4396, 3158, 4043, 4695], [2015, 4276, 202, 3279, 838, 4043, 2154, 4100], [1781, 829, 623, 2482, 4208, 2285, 3311, 1781, 255, 1864, 200], [3821, 4074, 767], [3039, 2905, 3906, 4958, 465, 255, 1864, 200], [1495, 852, 1949, 960, 147, 1534, 2531, 733, 2759, 4100], [643, 1511, 2347, 2433, 1551, 3195, 4945, 4425, 255, 1864, 200], [1504, 2500, 3010, 2260, 1081, 2225, 2262], [1275, 480, 4995, 1962, 2711, 3569, 1875, 2017], [4067, 2514, 910, 3987, 4308, 3492, 3674, 3104, 4015, 4185, 4523], [2683, 3300, 137, 858, 4216, 859, 523, 1602, 2565, 2805, 451, 4591], [2500, 2781, 1248, 38, 2366], [4219, 3898, 4043, 1985, 1593, 4830, 3093, 255, 1864, 200], [2242, 4044, 598, 1797, 245, 2565, 255, 1864, 200], [479, 2321, 2890, 4432, 139, 2242], [255, 4538, 2771, 1650, 492, 971, 358, 255, 1864, 200], [2078, 3203, 1650, 2759, 4830, 217, 217], [929, 275, 577, 4419, 1057, 4958, 255, 1864, 200], [], [1776, 579, 1858, 3158, 1776, 1404, 1508, 313], [1836, 4992, 1711, 2685, 3585, 4502, 4124, 2035, 3731, 2565], [1248, 3140, 2255, 3483, 4762, 4493, 4100], [852, 4899, 4722, 496, 1493, 633, 3906, 1516, 255, 1864, 200], [2992, 3959, 3604, 4577, 4969, 3997], [4437, 1082, 1447, 414, 4526, 2783, 2724, 4350, 1696, 3959, 4100], [4695, 4103, 1964, 4626, 3987, 1391, 2426, 2179], [2181, 3940, 312, 4037, 3820], [4043, 3581, 3443, 551, 1766, 4221, 1504, 1683, 1598, 255, 1864, 200], [4878, 3779, 4183, 4043, 4421, 1834, 2181, 3820, 4100], [3012, 625, 4357, 4043], [2941, 4471, 1625, 2711, 854, 2516, 1765], [2189, 2255, 2731, 551, 2193, 1137, 4213], [1665, 2023, 1981, 1072, 2941, 3793, 537, 1438, 339], [4286, 312, 4468, 135, 4043, 1688], [1504, 2827, 2835, 4043, 1256, 2769, 2904, 4354, 1137, 3067, 255, 1864, 200], [2671, 2295, 1006, 1953, 405, 673, 2295, 2711, 451], [4523, 488, 1696, 4211, 4754, 1953, 876, 494, 3154, 1826, 255, 1864, 200], [3983, 4972, 3352, 1172, 1172, 1172, 255, 1864, 200], [935, 4213, 4184, 760, 2807], [2793, 304, 15, 1442, 4211, 3868, 1998, 595], [2500, 4778, 

In [20]:
#Embedding presentation
sent_length = 20
embedded_docs = pad_sequences(onehot_repr , padding = 'pre', maxlen = sent_length)
embedded_docs

array([[   0,    0,    0, ..., 2666,  713, 1639],
       [   0,    0,    0, ..., 1696, 3131, 4100],
       [   0,    0,    0, ..., 1662, 3165, 2773],
       ...,
       [   0,    0,    0, ...,  255, 1864,  200],
       [   0,    0,    0, ..., 3957,  782, 3997],
       [   0,    0,    0, ..., 4882,  208, 2073]])

In [43]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

C:\Users\91979\OneDrive\Desktop\python.project\Annaconda\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [51]:
import numpy as np
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [53]:
##train test split 
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x_final, y_final, test_size = 0.2, random_state = 23)

In [55]:
#model trainig 
model.fit(x_final, y_final, validation_data = (x_test, y_test), epochs = 10,batch_size = 32)

Epoch 1/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.8589 - loss: 0.3046 - val_accuracy: 0.9514 - val_loss: 0.1205
Epoch 2/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9536 - loss: 0.1236 - val_accuracy: 0.9808 - val_loss: 0.0749
Epoch 3/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9731 - loss: 0.0763 - val_accuracy: 0.9875 - val_loss: 0.0500
Epoch 4/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9810 - loss: 0.0549 - val_accuracy: 0.9913 - val_loss: 0.0305
Epoch 5/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9903 - loss: 0.0327 - val_accuracy: 0.9966 - val_loss: 0.0169
Epoch 6/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9935 - loss: 0.0193 - val_accuracy: 0.9962 - val_loss: 0.0154
Epoch 7/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9937 - loss: 0.0194 - val_accuracy: 0.9976 - val_loss: 0.0094
Epoch 8/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9965 - loss: 0.0105 - val_accuracy: 0.9976 - val_loss: 0.0080
Epoch 9/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9984 - loss: 0.0062 - val_accuracy: 0.9993 - val_loss: 0.0029
Epoch 10/10
650/650 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9980 - loss: 0.0061 - val_accuracy: 0.9986 - val_loss: 0.0038

In [57]:
y_pred = model.predict(x_test)

130/130 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [81]:
import numpy as np

# If y_pred is a tuple, convert it to a numpy array
y_pred = np.array(y_pred)

# Now apply the threshold
y_pred = np.where(y_pred >= 0.5, 1, 0)

print(y_pred)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]]

In [87]:
print(f"Shape of y_test: {y_test.shape}")
print(f"Shape of y_pred: {y_pred.shape}")

Shape of y_test: (4160,)
Shape of y_pred: (2, 2068)

In [99]:
y_pred = model.predict(x_test)  # Make predictions on the test set
y_pred = (y_pred >= 0.5).astype(int)  # For binary classification, threshold predictions

130/130 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [103]:
y_pred = np.argmax(model.predict(x_test), axis=1)  # For multi-class classification

130/130 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [105]:
print(f"Length of y_test: {len(y_test)}")
print(f"Length of y_pred: {len(y_pred)}")

Length of y_test: 4160
Length of y_pred: 4160

In [111]:
from sklearn.metrics import confusion_matrix, accuracy_score
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[2098    0]
 [2062    0]]

In [117]:
accuracy_score(y_test, y_pred)

0.5043269230769231